spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-name
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: YOUR_KAKAO_REST_API_KEY
            redirect-uri: YOUR_KAKAO_REDIRECT_URI
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email

springdoc:
  packages-to-scan: com.paladyn.template
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8

# JWT
jwt:
  secret-key: YOUR_JWT_KEY_YOUR_JWT_KEY_YOUR_JWT_KEY_YOUR_JWT_KEY

server:
  error:
    whitelabel:
      enabled: false
